name = "starmc-wiki"
account_id = "0f0103845b5e7652f7ff394f2cde3098"
compatibility_date = "2026-05-05"

# Cloudflare Pages 配置
pages_build_output_dir = "./dist"

# 构建命令
# npm run build 会自动运行 prebuild 生成导航

[env.production]
name = "starmc-wiki"
pages_build_output_dir = "./dist"
